// Copyright 2024 Santosh Kumar (@santosh)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define TRI_LAYER_LOWER_LAYER 1
#define TRI_LAYER_UPPER_LAYER 2
#define TRI_LAYER_ADJUST_LAYER 3
#define SPLIT_WPM_ENABLE
#define RGBLIGHT_SPLIT
#define RGBLIGHT_SLEEP
#define RGBLIGHT_LAYERS

//#define NO_ACTION_TAPPING	//needed?
//
/* ws2812 RGB LED */
#define WS2812_DI_PIN D3
#define RGBLIGHT_DEFAULT_HUE 85

#ifdef RGBLIGHT_ENABLE
	#undef RGBLIGHT_ANIMATIONS
	#undef RGBLIGHT_EFFECT_ALTERNATING
	#undef RGBLIGHT_EFFECT_BREATHING
	#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
	#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
	#undef RGBLIGHT_EFFECT_SNAKE
	#undef RGBLIGHT_EFFECT_KNIGHT
	#undef RGBLIGHT_EFFECT_CHRISTMAS
	#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
	#undef RGBLIGHT_EFFECT_RGB_TEST
	#undef RGBLIGHT_EFFECT_TWINKLE
	#define RGBLIGHT_LAYERS_RETAIN_VAL
	#undef RGBLIGHT_LED_COUNT
    #define RGBLIGHT_LED_COUNT 32
	#undef RGBLED_SPLIT
	#define RGBLED_SPLIT { 16, 16 } 
    #undef RGBLIGHT_LIMIT_VAL
    #define RGBLIGHT_LIMIT_VAL 255
    #define RGBLIGHT_HUE_STEP 8
    #define RGBLIGHT_SAT_STEP 17
    #define RGBLIGHT_VAL_STEP 17
#endif

